language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 5.8
  - 6.0
  - 8.2
  - 6.1
  - hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: phpunit
